# Site settings
title: fullStack Dancers
email: fullstackdancers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are dancers, not developers
baseurl: "/fullstack-dancers" # the subpath of your site, e.g. /blog/
url: "http://rodrigo-kayala.github.io/fullstack-dancers" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
